### PR TITLE
V3 Major version update to use github.com/MicahParks/jwkset

### PR DESCRIPTION
**Pull request by MicahParks**
The purpose of this pull request is to do a major version upgrade.

This upgrade removes most of the code in this repository and outsources JWK and JWK Set related code to the updated [`github.com/MicahParks/jwkset`](https://github.com/MicahParks/jwkset) package. The exported assets from the `keyfunc` project has been vastly reduced as well, with the intention of making it easier to use for the majority of use cases. A superset of features is still available, through the use of this new dependency.

I encourage anyone interested in this project to comment on v3 before it is merged. I plan on merging this on Friday.

### CODE REVIEW

**Comment by bdwyertech** [comment]
@MicahParks I think it might be helpful to have an example for replacement of `kerfunc.MultipleJWKS`.  I'm using this to accept JWT's from multiple OIDC providers, some requiring special clients with authentication (K8S in-cluster).  Struggling a bit to understand the migration path, looks like jwksets has a DefaultHTTP and the httpstorage has an option for a client, can't seem to wrap my head around how to use it.

```go
                 providers := map[string]keyfunc.Options{}
                 // ....some other providers good with regular client
		providers[c.Host+"/openid/v1/jwks"] = keyfunc.Options{
			Client: client,
			RefreshErrorHandler: func(err error) {
				log.Errorf("error with the jwt.Keyfunc\nError: %v", err)
			},
			RefreshInterval:   time.Hour,
			RefreshRateLimit:  time.Minute * 5,
			RefreshTimeout:    time.Second * 10,
			RefreshUnknownKID: true,
		}
	        if jwks, err = keyfunc.GetMultiple(providers, keyfunc.MultipleOptions{}); err != nil {
		        return fmt.Errorf("failed to create JWKS from resource at the given URL.\nError: %w", err)
	        }
```

**Comment by MicahParks** [comment]
> @MicahParks I think it might be helpful to have an example for replacement of `keyfunc.MultipleJWKS`. I'm using this to accept JWT's from multiple OIDC providers, some requiring special clients with authentication (K8S in-cluster... smh). Struggling a bit to understand the migration path, looks like jwksets has a DefaultHTTP and the httpstorage has an option for a client, can't seem to wrap my head around how to use it.
> 
> Example:
> 
> ```go
>                  // K8S Client
> 		l := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(clientcmd.NewDefaultClientConfigLoadingRules(), nil)
> 		c, err := l.ClientConfig()
> 		if err != nil {
> 			return err
> 		}
> 		client, err := rest.HTTPClientFor(c)
> 		if err != nil {
> 			return err
> 		}
>                  providers := map[string]keyfunc.Options{}
>                  // ....some other providers good with regular client
> 		providers[c.Host+"/openid/v1/jwks"] = keyfunc.Options{
> 			Client: client,
> 			RefreshErrorHandler: func(err error) {
> 				log.Errorf("error with the jwt.Keyfunc\nError: %v", err)
> 			},
> 			RefreshInterval:   time.Hour,
> 			RefreshRateLimit:  time.Minute * 5,
> 			RefreshTimeout:    time.Second * 10,
> 			RefreshUnknownKID: true,
> 		}
> 	        if jwks, err = keyfunc.GetMultiple(providers, keyfunc.MultipleOptions{}); err != nil {
> 		        return fmt.Errorf("failed to create JWKS from resource at the given URL.\nError: %w", err)
> 	        }
> ```

@bdwyertech great question, thank you for asking.

The new v3 interface is intended to simplify the public facing API for the majority of use cases, while providing deeper customization through the `github.com/MicahParks/jwkset` dependency.

Based on the example you've given, it looks like your use case does fit nicely into the new API because of the non-default HTTP client. I'm going to make an advanced example now and publish it now.

**Comment by MicahParks** [comment]
@bdwyertech, here is a snipppet from the newly created advanced example:
https://github.com/MicahParks/keyfunc/blob/5dbebf7dfb84a260c4543d6d54ec1583503a4ae1/examples/advanced/main.go#L77-L92

This snippet shows a per URI HTTP client configuration that uses a custom HTTP client.

It's certainly more code than the default:
https://github.com/MicahParks/keyfunc/blob/5dbebf7dfb84a260c4543d6d54ec1583503a4ae1/examples/http/main.go#L70-L74

I would be open to suggestions about how to make customization easier for package users. Constructive criticism is welcome.

**Comment by bdwyertech** [comment]
@MicahParks thank you sir!  I will give this a look tomorrow.

**Pull request merged**
