### PR TITLE
Default to having the keyfunc() method only return keys appropriate for signature validation

### PR DESCRIPTION
**Pull request by trevorlyman**
This PR is associated with this original [PR](https://github.com/MicahParks/keyfunc/pull/54).

### CODE REVIEW

**Comment by MicahParks** [comment]
Here's a link to the original issue as well: https://github.com/MicahParks/keyfunc/issues/53

Thank you @trevorlyman!

**Comment by MicahParks** [comment]
> I wanted to make sure you ended up on the [contributors page](https://github.com/MicahParks/keyfunc/graphs/contributors), so I selected the rebase and merge option. However, I think it had the opposite effect. I think I should have used the first option, the merge commit.

It looks like one or more of my thoughts here were incorrect. My current thoughts are that the contributors will update during the next release. If that's not the case, I'll troubleshoot further to get you on the [contributors page](https://github.com/MicahParks/keyfunc/graphs/contributors), @trevorlyman.

**Comment by MicahParks** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#common-reasons-that-contributions-are-not-counted

> Commit was made less than 24 hours ago

I do know that it's taken the contributors page quite some time to update in the past. Maybe this is the root cause of it not updating.

> Your local Git commit email isn't connected to your account

Is it possible that the email you've used isn't associated with your GitHub account?

**Comment by trevorlyman** [comment]
> 

I think it will show up in the next 24 hours. I used an email that was not linked with my GitHub account initially. I've now since linked it. The GitHub documentation says it can take up to 24 hours to get linked up.

**Comment by MicahParks** [comment]
Looks like the commits from when I merged with the rebase and merge method do show up on your profile for contributions to this project: https://github.com/MicahParks/keyfunc/commits?author=trevorlyman

I'm including this for anyone whose searching for if the rebase and merge method adds a new contributor to your repository because this is something I searched for a few hours ago.

**Pull request merged**
